### PR TITLE
Fixed bug in concatenation file

### PR DESCRIPTION
**Pull request by jmaxey**
Fixed the frame count error in the file.

@kimtonyhyun

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
Checking it out

**Comment by kimtonyhyun** [comment]
I just tried out this code on c9m7d09 (which has a non-glitched PlusMaze text file). I expected the concatenated (and trimmed) movie to have 46228 frames, but found only 46226 in the resulting HDF5. Is the current code correctly writing in the dropped frames into the HDF5?

**Comment by jmaxey** [comment]
Let me check. I may need to alter something else since the dropped frames are in the first cropped 15. 

----- Original Message -----

**Comment by kimtonyhyun** [comment]
Same on c9m7d06, the concatenated result is 2 frames shorter than expected.

**Comment by kimtonyhyun** [comment]
Does `concatenateHDF5` assume that the first file is always a valid trial? This assumption may be false in some cases, if we needed to do a repeat on the first trial.

**Comment by jmaxey** [comment]
I know what's wrong and am working to fix it now. I will make sure that dropping the first frame is not a problem.

----- Original Message -----

**Comment by jmaxey** [comment]
I have to go to office hours soon and then have class but will keep working on it. Sorry for the delay.

----- Original Message -----

**Comment by kimtonyhyun** [comment]
Outdated -- closing.

**Pull request closed without merging**
