### PR TITLE
Fixed bug in concatenation script

### PR DESCRIPTION
**Pull request by jmaxey**
I believe that the bug has been fixed, however, I have not had a chance to test this on my computer at CNC.  Please feel free to go ahead and run it (knowing that there might still be an error). I will be by Herrin this afternoon to test it.
@kimtonyhyun

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
Checking it now. Can you unstage `.DS_Store` (and add it to `.gitignore`)?

**Comment by kimtonyhyun** [comment]
```
>> concatenateHDF5(pwd,pwd,'c9m7d09.hdf5',1,'mouse7_day09_allo-south.txt',[15 5]);
Error using tifflib
Unable to change to directory with dirnum = 583.

Error in Tiff/setDirectory (line 1280)
            tifflib('setDirectory',obj.FileID,dirNum-1);

Error in concatenateHDF5 (line 94)
                tifFile.setDirectory(j+trim(1));
```

**Comment by kimtonyhyun** [comment]
Why is it going to `tifflib` for HDF5 concatenation

**Comment by jmaxey** [comment]
It has to use tifflib to read in the original files. I know what the problem is though (it doesn't have anything to do with tifflib - its an indexing problem). Fixing it now.

**Comment by kimtonyhyun** [comment]
Looks like it works! Can you remove `.DS_Store` (used by Mac filesystem) from the PR, and add it to `.gitignore`?

**Comment by kimtonyhyun** [comment]
I'll merge it and remove the dangling files.

**Pull request merged**
