### PR TITLE
Added varargout "trial_frames" generated by find_start_end_of_trials

### PR DESCRIPTION
**Pull request by forea**
Small change to mouse_path_plotter code to also spit out trial_frames from behavior movie if no plusmaze data was provided (i.e. function had to figure out trial_frames on its own)

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
How about always outputting `trial_frames`, rather than using `varargout`? (The calling function doesn't always have to receive the output.)

**Comment by forea** [comment]
Cool, I didn't know that was possible. Updated!

**Comment by kimtonyhyun** [comment]
By the way, does `trial_idx = 1:length(trial_frames)` work? Since `trial_frames` is `[n x 2]` I thought that one needs to write `trial_idx = 1:size(trial_frames,1)`

**Comment by forea** [comment]
It works. L = length(X) returns the length of the largest array dimension in X... so its possible if there were only 1 trial it would be wrong. I guess size(trial_frames,1) is more accurate.

http://www.mathworks.com/help/matlab/ref/length.html.

**Comment by kimtonyhyun** [comment]
We should write `size(trial_frames,1)` in cases like this -- to err on the side of explicit. Otherwise (though probably not in this case), we may run into hard-to-debug scenarios.

**Comment by forea** [comment]
Yep, updated

**Comment by kimtonyhyun** [comment]
Looks good to me.

**Pull request merged**
