### PR TITLE
add metric for sorting cells

### PR DESCRIPTION
**Pull request by inanhkn**
I added a metric that looks at a trace and determines how spiky it is. This is now implemented in `extract_cells.m` and cells are sorted taking this metric into account. The script now gives additional command line output during execution like the the following:

```
27-Aug-2015 16:56:21: Cell Statistics:
 			 First 445 extracted cells are likely to be cells
 			 It is likely that there are few or no cells from  #712 onwards
```

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
Am I supposed to run `extract_cells` on the PCA file that you just put on LY-imaging? Can you run `extract_cells` on the PCA file on your computer and give me a link (e.g. Dropbox) to the rec file? (LY-imaging is still motion correcting today's m5 movie.)

**Comment by inanhkn** [comment]
Yes, that's right. Here's the link to the rec file:
https://www.dropbox.com/s/mxkvxe6cyvhl848/rec_150827-171046.mat?dl=0

**Comment by kimtonyhyun** [comment]
Would `extract_cells` have worked on a machine with 32 GB RAM (e.g. reuniens)?

**Comment by inanhkn** [comment]
Yes. It occupies memory roughly equal to <movie size> + 2*<pca file size>.

**Comment by kimtonyhyun** [comment]
A quirk of PCA+SSS appears to be that it doesn't like to generate "oblong" cells. For example, cells 330 and 478 are splitting one oblong cell at the edge of the field of view:
image

The traces are pretty much identical too:
cell330
cell478

I've noticed this pattern frequently -- that oblong cells in the movie are split into multiple generally-circular cells. How can we fix this?

**Comment by kimtonyhyun** [comment]
Maybe something like this could be helpful?: http://labrigger.com/blog/2013/06/13/local-cross-corr-images/

**Comment by kimtonyhyun** [comment]
Another pair:
image
cell281
cell471

**Comment by kimtonyhyun** [comment]
Final result is 358 classified cells of 734 on c11m1d12:
image

To be benchmarked against 424 of 888 on the same movie via CellMax. The following plot shows the overlapped cell maps (CellMax is blue; SSS is red):
image

Current conclusions:
- The two methods overlap quite nicely on a large number of cells -- this makes me feel comfortable with both extraction methods. (Trace-level comparisons to come.)
- There are cells that SSS catches that CM did not; and visa versa. CM exceeds SSS in net number of cells.
- Generally, SSS does not seem to be very happy with oblong cells, e.g. at the left side of the FOV. Oblong cells are often split into multiple sources. See example below.

Splitting of oblong cells. Here's cell 769 of CM, which has been split into 3 sources by SSS:
image

Here is its CM trace and raster plot, which shows that it has a decent SNR and potentially coding properties in the task:
image

I would thus propose improved handling of oblong cells in SSS.

**Comment by kimtonyhyun** [comment]
In this comparison, I am plotting only the classified cells of CellMax (424 cells, shown in blue) against _all_ SSS cells (shown in red). The comparison shows how the SSS can: (1) split large, oblong cells, or (2) doesn't capture the full ROI of the cell:
image
image

**Comment by forea** [comment]
Same SSS extraction, I counted 344 cells
[image: Inline image 1]

**Comment by kimtonyhyun** [comment]
Here's the comparison between Fori and my classification on c11m1d12 SSS:
image

Overlaid (Fori red; Tony blue):
image

**Comment by forea** [comment]
Same SSS extraction, I counted 344 cells
cell_map

**Comment by kimtonyhyun** [comment]
The number of cells in agreement between Fori and my classification is 321. So, using 344 as the denominator, the agreement is 93.3% -- quite high.

Here's a code snippet that shows how to do the calculation quickly with `DaySummary`:
```

>> m1d12_sss2 = DaySummary(sources.maze, 'sss2');
  28-Aug-2015 19:17:21: Loaded filters/traces from sss2\rec_150827-171046.mat
  28-Aug-2015 19:17:21: Loaded classification from sss2\class_150828-092948.txt
>> m1d12_sss2_fori = DaySummary(sources.maze, 'sss2_fori');
  28-Aug-2015 19:17:45: Loaded filters/traces from sss2_fori\rec_150827-171046.mat
  28-Aug-2015 19:17:45: Loaded classification from sss2_fori\class_150828-115534.txt
>> sum(m1d12_sss2.is_cell & m1d12_sss2_fori.is_cell)

ans =

   321
```

**Comment by kimtonyhyun** [comment]
Merging for now. Let me know with another PR once you want me to take a look at a revised extraction result.

**Pull request merged**
