### PR TITLE
Jmaxey hdf5

### PR DESCRIPTION
**Pull request by jmaxey**
It should be working now. If the dropped files were in the first 15 frames, it was incorrectly ignoring them. While those particular frames might not be kept in the final video, other are moved out of the 15 frames once the duplicates are added and should be included the final video (and they were previously not).
@kimtonyhyun

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
Checking out the code now -- however, this PR can't be merged because there's a conflict with master. (This branch is probably based off of an old version of master.) Can you look at the merge conflict?

**Comment by kimtonyhyun** [comment]
I've got a problem with `concatenateHDF5` looking for an extra trial again:
```
>> concatenateHDF5(pwd, pwd, 'c9m6d19.hdf5', 1, 'mouse6_day19_allo-north.txt', [15 5]);
File 1 of 107 stored
File 2 of 107 stored
File 3 of 107 stored
File 5 of 107 stored
DroppedFrame
DroppedFrame
File 6 of 107 stored
File 7 of 107 stored
File 8 of 107 stored
File 9 of 107 stored
File 10 of 107 stored
File 11 of 107 stored
File 12 of 107 stored
File 13 of 107 stored
File 14 of 107 stored
File 15 of 107 stored
File 16 of 107 stored
File 17 of 107 stored
File 18 of 107 stored
File 19 of 107 stored
File 20 of 107 stored
File 21 of 107 stored
File 22 of 107 stored
File 23 of 107 stored
File 24 of 107 stored
File 25 of 107 stored
File 26 of 107 stored
File 27 of 107 stored
File 28 of 107 stored
File 29 of 107 stored
File 30 of 107 stored
File 31 of 107 stored
File 32 of 107 stored
File 33 of 107 stored
File 34 of 107 stored
File 35 of 107 stored
File 36 of 107 stored
File 37 of 107 stored
File 38 of 107 stored
File 39 of 107 stored
File 40 of 107 stored
File 41 of 107 stored
File 42 of 107 stored
File 43 of 107 stored
File 44 of 107 stored
File 45 of 107 stored
File 46 of 107 stored
File 47 of 107 stored
File 48 of 107 stored
File 49 of 107 stored
File 50 of 107 stored
File 51 of 107 stored
File 52 of 107 stored
File 53 of 107 stored
File 54 of 107 stored
File 56 of 107 stored
File 57 of 107 stored
File 58 of 107 stored
File 60 of 107 stored
File 61 of 107 stored
File 62 of 107 stored
File 64 of 107 stored
File 65 of 107 stored
File 66 of 107 stored
File 67 of 107 stored
File 68 of 107 stored
File 69 of 107 stored
File 70 of 107 stored
File 71 of 107 stored
File 72 of 107 stored
File 75 of 107 stored
File 76 of 107 stored
File 77 of 107 stored
File 78 of 107 stored
File 79 of 107 stored
File 80 of 107 stored
File 81 of 107 stored
File 82 of 107 stored
File 83 of 107 stored
File 84 of 107 stored
File 85 of 107 stored
File 86 of 107 stored
File 87 of 107 stored
File 88 of 107 stored
File 89 of 107 stored
File 90 of 107 stored
File 91 of 107 stored
File 92 of 107 stored
File 93 of 107 stored
File 94 of 107 stored
File 95 of 107 stored
File 96 of 107 stored
File 97 of 107 stored
File 98 of 107 stored
File 99 of 107 stored
File 100 of 107 stored
File 101 of 107 stored
File 102 of 107 stored
File 103 of 107 stored
File 104 of 107 stored
File 105 of 107 stored
File 106 of 107 stored
Attempted to access frame_indices(101,2); index out of bounds because
size(frame_indices)=[100,4].

Error in concatenateHDF5 (line 130)
        gateUpFrame = totalFrames + (frame_indices(trialCount,2) -
        frame_indices(trialCount,1) - trim(1));
```

**Comment by kimtonyhyun** [comment]
Oops sorry, I wasn't on the latest version of your branch. Checking again!

**Comment by kimtonyhyun** [comment]
Worked! Will merge once the conflict is fixed.

**Comment by jmaxey** [comment]
Any idea how to fix the conflict? I deleted my local repository and recloned the master before generating the pr so I'm not sure what else I can do.

Jessica

**Comment by kimtonyhyun** [comment]
Here's what you should do:

1. Go to the master branch and pull the latest changes (`git pull`)
2. Go into your branch "jmaxey-hdf5" (`git checkout jmaxey-hdf5`)
3. Merge the latest changes from master onto "jmaxey-hdf5" (`git merge master`)

You will then be notified of a merge conflict, like this:
```
compute3@compute3:~/Documents/analysis$ git checkout jmaxey-hdf5
Branch jmaxey-hdf5 set up to track remote branch jmaxey-hdf5 from origin.
Switched to a new branch 'jmaxey-hdf5'
compute3@compute3:~/Documents/analysis$ git pull origin jmaxey-hdf5
From https://github.com/inanhkn/analysis
 * branch            jmaxey-hdf5 -> FETCH_HEAD
Already up-to-date.
compute3@compute3:~/Documents/analysis$ git merge master
Auto-merging view/view_superimposed_trials_in_trace.m
Auto-merging io/miniscope/count_frames_in_xml.m
Auto-merging io/concatenateHDF5.m
CONFLICT (content): Merge conflict in io/concatenateHDF5.m
Removing io/bin_frame_indices.m
Removing image_op/compute_mean_fluorescence.m
Automatic merge failed; fix conflicts and then commit the result.
```

The conflict occurs in `concatenateHDF5`. You can open the file in editor, and you will see a few segments like this (ignore the line numbers and the $ at the end of each line -- that's just from my editor):
```
124 <<<<<<< HEAD$
125                 frontStack = imageStack(:,:,1:droppedFrame-1);$
126                 frontStack = cat(3,frontStack,imageStack(:,:,droppedFrame-1));$
127                 backStack = imageStack(:,:,droppedFrame:end);$
128                 newImageStack = cat(3,frontStack,backStack);$
129                 clear imageStack$
130                 imageStack = newImageStack;$
131                 numDroppedFrames = numDroppedFrames+1;$
132 =======$
133                 if((droppedFrame > trim(1)) && (droppedFrame < oriFrames-trim(2)))$
134                     droppedFrame = droppedFrame+trim(1);$
135                     frontStack = imageStack(:,:,1:droppedFrame-1);$
136                     frontStack = cat(3,frontStack,imageStack(:,:,droppedFrame-1));$
137                     backStack = imageStack(:,:,droppedFrame:end);$
138                     newImageStack = cat(3,frontStack,backStack);$
139                     clear imageStack$
140                     imageStack = newImageStack;$
141                 else$
142                     cropDroppedFrames = cropDroppedFrames+1;$
143                 end$
144 >>>>>>> master$
```

The interpretation is that the first segment (`<<<<<<< HEAD`) is what's on your branch (jmaxey-hdf5), and the segment after the `=======` is what's on master. Git was unable to automatically figure out how to combine the changes.

You need to resolve each of these conflicting regions. For example, if you want to keep everything as it exists on jmaxey-hdf5, then erase all the lines between `=======` and `>>>>>>> master`.

The final file should not have any `<<<<<<< HEAD`, `=======`, `>>>>>>> master` markers.

Once all conflicts are resolved, commit the result, and push back to the remote repository (`git push origin jmaxey-hdf5`).

* * *

As a general comment, to minimize the chance for merge conflicts, you should create new branches for new "features" from the most fresh version of master, rather than kicking along old branches in parallel, since then the branch can diverge from master over time.

**Comment by jmaxey** [comment]
Fixed!

----- Original Message -----

**Pull request merged**
