### PR TITLE
Kimth/ds rasters

### PR DESCRIPTION
**Pull request by kimtonyhyun**
Added a "raster browser", to allow for quick review of multiple cell rasters of a single day (i.e. of a single `DaySummary`). The tool can be used as follows.

First, you need to have a classified `DaySummary` (the browser tool will only display rasters of confirmed/classified cells):
```
>> sources = data_sources

sources = 

         maze: '_data/c11m3d15_ti2.txt'
    miniscope: '_data/c11m3d15_gfix_cr_rm_mc_cr_norm_dff_ti2.hdf5'
          pca: '_data/pca_n700.mat'
          fps: 10

>> m3d15 = DaySummary(sources.maze, 'rec001', 'reconst', 'excludeprobe');
  14-Aug-2015 13:31:30: Loaded data from rec001/rec_150813-115003.mat
  14-Aug-2015 13:31:30: Loaded classification from rec001/class_150813-115320.txt
```

The raster browser can be invoked by the following:
```
>> browse_rasters(m3d15);
```
which yields the following figure:
browse_page1
(The number of subplots per page is configurable, and may be added as a configurable option in the future.)

You are also asked for a response in the prompt:
```
Raster viewer (page 1 of 25) >> 
```

For instance, you can type `n` for "next page" (or `p` for "previous page"):
```
Raster viewer (page 1 of 25) >> n
Raster viewer (page 2 of 25) >> 
```
which shows the following page of rasters:
browse_page2

You can also jump to a particular cell index by typing the number directly. Below, we jump to the page that contains cell 62:
```
Raster viewer (page 3 of 25) >> 62
  Cell 62 selected!
Raster viewer (page 10 of 25) >> 
```
browse_page10

Now, if you ask for a cell index that is already in the currently displayed page (i.e. cell 62 again in the current example), you will be shown a detailed raster plot of that particular cell:
```
Raster viewer (page 10 of 25) >> 62
  Cell 62 selected!
  Press any key to return to all cells...
```
cell62

The idea with the single-cell rasters to see if the activity can be easily parsed in the basis of:
- Trial correctness / incorrectness
- Start location (east / west)
- End location (south / north)
For example, I would argue that cell 62 in the current example do not have a "simple" explanation in terms of the above three bases.

You can return to all rasters by pressing any key to escape from the single cell raster viewer.

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
I also added a helper function `allcomb` from the Matlab Exchange, and also deprecated an old visualization code (`plot_trial_raster`) that was no longer being used.

**Comment by forea** [comment]
this is nice!

would it make sense to add ability to save a picture of cells of interest (in the detailed view w/ breakdown)? :)

**Comment by kimtonyhyun** [comment]
Ah yes, I'll add the option `t` (to "take screenshot") in the detailed view, and reping.

**Comment by kimtonyhyun** [comment]
You can now take a screenshot of a detailed single cell raster by typing `t` in the prompt window:
```
Raster browser (page 1 of 24) >> 2
  Cell 2 selected!
Cell 2 raster >> t
  Saved raster as "raster_2.png"!
```

**Pull request merged**
