### PR TITLE
Kimth/classify pairs

### PR DESCRIPTION
**Pull request by kimtonyhyun**
Please do not merge before everyone has had a chance to try out the branch!

This PR adds the ability to:

1. Generate localized ROIs from ICA filters and apply the resulting filters to the DFF movie  (`reconstruct_traces.m`). In the case that the IC results in multiple "blobs", the script will prompt for which ROIs to keep.
2. Classify the resulting reconstructed filters/traces (`classify_cells.m`).
3. Modifications to `DaySummary` and `run_alignment` so that they are compatible with the reconstructed traces.

__Note__: Previously, ICA results were stored in `ica_(...).mat` files with the variable names `ica_info`, `ica_traces`, `ica_filters`. Now, I've renamed these internal variables to be `info`, `traces`, `filters` respectively. This means that you will have to generate new ICA mat files, to be able to try out the reconstructed filters workflow.

Here's a walkthrough.

#### 1) Run ICA as usual by:
```
>> sources = data_sources

sources = 

         maze: '_data/c9m7d07_ti2.txt'
    miniscope: '_data/c9m7d07_cr_mc_cr_norm_dff_ti2.hdf5'
          pca: '_data/pca_n500.mat'
          fps: 10

>> run_ica(sources.pca, 250, 0.1);
```
and place the resulting ICA `*.mat` files in its own directory, i.e. `ica002`.

#### 2) Run `reconstruct_traces` as follows:
```
reconstruct_traces(sources.miniscope, 'ica002');
```
If the function encounters an IC filter with multiple ROIs, then it will prompt you to specify the ROIs to keep. For example:
20150326_roi-prompt

Here, I want to keep ROIs 1 and 2 (note that the green/red color means nothing -- just to disambiguate the ROIs when they are spatially close):
```
26-Mar-2015 15:20:40: Please select ROIs to keep from IC 57
  >> 1
  >> 2
  >> 
    Added ROI 1 from IC 57
    Added ROI 2 from IC 57
```
You can also choose to disregard all ROIs by just pressing enter without specifying any ROIs.

When done specifying ROIs, `reconstruct_traces` will load the DFF movie and apply the ROI filters onto the movie. Resulting "reconstructed" filters and traces will be stored in a `rec_(...).mat` file. Place that in its own directory, e.g. `ica002_rec1`.

#### 3) Run `classify_cells` as follows:
```
>> classify_cells(sources, 'ica002_rec1', 'reconst');
```
Here, the `reconst` toggle specifies that we are looking for a `rec_(...).mat` file. (The classification script is also compatible with `ica_(...).mat` file -- as long as the ICA outputs are generated by the updated `run_ica`.)

Note: I left `classify_ics` alone, so that that script is compatible with the previously-generated ICA `*.mat` files. We'll deprecate it over time.

The classification proceeds as usual. Place the classification text file in `ica002_rec1` directory (same place as the `rec_(...).mat` file) when done.

#### 4) Load the resulting classified reconstructed filters/traces into `DaySummary`.

```
>> day7 = DaySummary(sources.maze, 'ica002_rec1', 'reconst');
```
The `reconst` toggle tells the `DaySummary` constructor to look for `rec_(...).mat` file in `ica002_rec1`, rather than `ica_(...).mat` file.

From this point on, `day7` may be manipulated as normal (i.e. no further distinction between ICA filter/traces and reconstructed filter/traces).

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
Added support for plotting cell map in `DaySummary`. For example:
```
ds.plot_cell_map();
```
yields:
day6_plotcellmap

(Note, I am somewhat concerned about `DaySummary` becoming too bloated. We might then start writing external functions that deal with `DaySummary` inputs, rather than writing more and more methods into the class.)

**Comment by kimtonyhyun** [comment]
Whoa, I am logged in as Jessica on this laptop!

**Comment by kimtonyhyun** [comment]
Wanted to point out a useful method of `DaySummary`. You can color-code the cell map as follows:
```
>> path_dep = [10 26 32 38 39 41 51 52 59 63 66 74 80 83 87 88 91 92 101 103 105 108 110 118 120 122 123 131 141 152 155 156 159 161 162 165 169 174 176 184 186 196 198 199 203 206 207 209 219 224 225 226 234 235 237 239 240 242 247 249];
>> path_indep = [45 56 57 60 61 64 67 71 73 75 90 93 95 96 98 99 104 107 111 112 115 116 124 126 135 138 139 140 143 144 145 149 151 160 163 166 167 170 181 183 185 187 190 191 192 193 197 202 208 213 214 216 220 223 228 229 232 233 244 255];
>> ds.plot_cell_map({path_dep, path_indep});
```

This will plot a cell map where the indices in `path_dep` are grouped in one color, and the indices of `path_indep` are grouped in another. The above command yields the following plot:
c9m7d06_ica04-rec01_map-path

**Comment by kimtonyhyun** [comment]
One more thing I forgot to note in the original PR description is that the behavior of `run_alignment` has now been changed as follows:

- Takes `DaySummary` objects as inputs, rather than directory name
- Supports one-to-one matching, i.e. a cell on one of the "days" (note that a DaySummary can also be the same day, but a different cell-extraction instance) will be matched to at most one cell of the other "day" -- and visa versa.

Example. Let `ds1` and `ds2` be `DaySummary` objects, then:
````
[match_1to2, match_2to1] = run_alignment(ds1, ds2, 'one-to-one')
```
will perform one-to-one matching between the two `DaySummary`s.

**Comment by kimtonyhyun** [comment]
Further update to `DaySummary`. The `DaySummary` now contains the mask of each cell (`ds.cells(k).mask`), which can also be retrieved via `ds.get_mask`.

Example use:
```
>> sources = data_sources

sources = 

         maze: '_data/c9m7d07_ti2.txt'
    miniscope: '_data/c9m7d07_cr_mc_cr_norm_dff_ti2.hdf5'
          pca: '_data/pca_n500.mat'
          fps: 10

>> day7 = DaySummary(sources.maze, 'ica004_rec01', 'reconst');
27-Mar-2015 21:05:05: Loaded data from ica004_rec01\rec_150327-161528.mat
>> cell_mask = day7.get_mask;
>> imagesc(cell_mask);
```
results in the following plot:
cellmask

Among other uses, the "cell mask" can now be used in combination with `view_movie` as follows:
```
>> M = load_movie(sources.miniscope);
>> view_movie(M, 'mask', cell_mask);
```
which will show a movie like:
viewmovie_mask

Similiarly,
```
>> view_movie(M, 'mask', ~cell_mask);
```
shows the following movie:
viewmovie_notmask

In particular, the latter movie is useful for getting a sense of whether we missed some cells in the DFF movie after the cell extraction process.

**Comment by kimtonyhyun** [comment]
Few more changes to `classify_cells`. The script uses `DaySummary` internally, which means that it can utilize the built-in visualization functions of `DaySummary`.

In the first presentation of a candidate cell, now also show raster representation of the trace:
raster-included

Once the user enters the movie playback mode, two new changes:
- The movie starts off zoomed in on the cell under consideration. (Use `z` to toggle between full and zoom, as before.)
- Also shows the boundary of other cells, not currently under consideration as a dashed yellow line. This is useful to see if a cell in the movie has been split into multiple ROIs.

show-nearby-cells

I'd like to deprecate the old `classify_ics` soon.

**Comment by kimtonyhyun** [comment]
Incidentally, with the highlighting of other cells during classification, it's super clear that we're still missing cells (even when I ask for 250 ICs to begin with). There are evident cells in the movie that are not captured in the yellow boundaries.

**Comment by jmaxey** [comment]
I'm working with EM right now and it seems to be working decently well. I'm playing with some thresholds to adapt it to the PreFrontal data but it looks promising.

----- Original Message -----

**Comment by kimtonyhyun** [comment]
Which day are you using for EM, and about how many cells are you picking up?

**Comment by jmaxey** [comment]
Have you been having any problems with git? My terminal keeps freezing when I try to input 'git add .' or 'git add --all'. 


----- Original Message -----

**Comment by jmaxey** [comment]
Its not working quite that well yet. I'm working with mouse 7 day 12 because I know its pretty clean. I've been debugging the event detection code this morning and think I might have it working now (although the classify cell function seems to be having a slight problem). 

----- Original Message -----

**Comment by kimtonyhyun** [comment]
Git is okay for me

**Comment by kimtonyhyun** [comment]
Cell regions now show their index as well:
cell-numbers

**Comment by kimtonyhyun** [comment]
The boundaries of other cells can be toggled on/off by typing `n`.

**Comment by forea** [comment]
I tried out the workflow except for alignment, so far no bugs

**Comment by forea** [comment]
alignment worked

- DaySummary breaks if `reconstruct_traces` spits out a filter that's all NaN's
- in `classify_cells`, sometimes threshold is too high (sometimes due to fluctuating baseline)

**Pull request merged**
