### PR TITLE
remove hot pixels

### PR DESCRIPTION
**Pull request by inanhkn**
The big computer won't let you go Tony..

With this script the hot pixels should not be a problem anymore. The script identifies the hot pixels and removes them by median filtering only those pixels. 
Example call: 
`remove_hot_pixels('c9m7d12.hdf5','');`

Important note: This script should be called before the motion correction is done since the hot pixels will start moving around after the motion correction.

### CODE REVIEW

**Comment by kimtonyhyun** [comment]
This works well enough for a few hot pixels (I tried on `c9m6d12`). On the other hand, it doesn't solve the issues for the Miniscope that has a ton of hot pixels (i.e. Mouse 2). Maybe we need to treat `c9m2` as a special case... I'll show you next time you are at Herrin.

**Comment by kimtonyhyun** [comment]
I bet the big computer has some sort of a global user setting, since I installed Github for Windows... Let me see if I can undo that.

**Comment by inanhkn** [comment]
Tony, did you set the maximum number of hot pixels to a higher value? You can set it to 1000 and it will remove exactly 1000 'hottest' pixels (the default is 30:) ). It will still be infinitely faster than median filtering all [height]x[width] number of pixels.

**Comment by inanhkn** [comment]
Also, if you think there are movies with many hot pixels adjacent to one another, let me know. I naively assumed that would not be the case. I can make changes that take that into account.

**Comment by kimtonyhyun** [comment]
Actually, with increased number of hot pixels (1500 for `c9m2d05`), the output movie looks much better. The PR looks good to me.

**Comment by kimtonyhyun** [comment]
Btw, I'm processing c9m2 now on the old big computer (`LY-imaging.stanford.edu`) using this filtering as the first step in the pipeline (after concatenation).

**Comment by inanhkn** [comment]
I have made a few minor additions that does not change the functionality. I'm merging it.

**Pull request merged**
